### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ewels**

### CODE REVIEW

**Comment by mashehu** [comment]
I don't see that logo appearing in the readme...

**Comment by mashehu** [comment]
Found them 🙃

**Review by mashehu — APPROVED** [review]

**Comment by ewels** [comment]
Yeah, it's here: https://github.com/nf-core/.github/blob/master/profile/README.md

Looks like the URL I used is broken though: https://raw.githubusercontent.com/nf-core/logos/master/nf-core-logos/nf-core-logo_logo_dark.png#gh-dark-mode-only

**Comment by ewels** [comment]
Fixed in https://github.com/nf-core/.github/commit/07337fce3629e0e667bbf123587a809931088a39 (pushed directly as was simple typo)

**Comment by ewels** [comment]
Ah goddam it, that was the wrong logo 😆

**Comment by ewels** [comment]
ok, _now_ it should be good: 25bbcbf01d27349bc60ba3db232f2aa22f19b1f9

**Pull request merged**
